services:
  pbx:
    image: portsip/pbx:22  # Especifique a imagem Docker a ser usada
    container_name: pbx
    volumes:
      - ./pbx_data:/opt/portsip  # Monta um volume para persistência de dados
    environment:
      - WORKSPACE=/opt/portsip
    ports:
      - "5061:5060"  # Exemplo de porta para SIP
      - "8080:8080"  # Exemplo de porta para interface web
    restart: unless-stopped
